import type { SignalDef } from "./types";

/**
 * Catálogo completo de señales. Las 1-40 son las del brief original
 * (no se modifican). Las 41-45 son señales extra que también delatan
 * una web hecha por IA o mal implementada.
 */
export const SIGNALS: SignalDef[] = [
  {
    code: 1,
    id: "generic-section-labels",
    title: "Etiquetas genéricas arriba de cada sección",
    category: "ia",
    severity: "media",
    why: "La IA rotula cada bloque con su nombre funcional (Testimonios, Servicios, FAQ). Nadie escribe así una web pensada: el contenido se explica solo.",
    fix: "Reemplazar cada rótulo por un titular con mensaje propio. En vez de Testimonios, algo como: Tres clientes que ya no pierden 6 horas por semana.",
  },
  {
    code: 2,
    id: "emoji-overload",
    title: "Exceso de emojis",
    category: "ia",
    severity: "media",
    why: "Los emojis usados como viñetas o decorando titulares son la firma visual de los generadores de landings.",
    fix: "Sacar los emojis del copy estructural. Si hace falta un ícono, usar íconos reales del sistema de diseño.",
  },
  {
    code: 3,
    id: "italic-abuse",
    title: "Abuso de texto en itálica",
    category: "diseno",
    severity: "baja",
    why: "La IA usa itálica para dar énfasis emocional en subtítulos y testimonios. En una web humana la itálica es rara y deliberada.",
    fix: "Eliminar las itálicas decorativas. Enfatizar con jerarquía tipográfica, peso o color.",
  },
  {
    code: 4,
    id: "no-favicon",
    title: "Sin favicon",
    category: "tecnico",
    severity: "media",
    why: "El favicon es lo primero que se olvida cuando la web se generó y se publicó sin revisar.",
    fix: "Agregar un favicon propio (ICO/SVG + apple-touch-icon) y declararlo en el head.",
  },
  {
    code: 5,
    id: "h1-problem",
    title: "Sin H1 o con varios H1",
    category: "seo",
    severity: "alta",
    why: "Una jerarquía rota (cero H1, o cinco) indica que nadie pensó la estructura semántica de la página.",
    fix: "Un único H1 por página, con la promesa principal. El resto en H2/H3 en orden.",
  },
  {
    code: 6,
    id: "no-legal-pages",
    title: "Sin términos ni política de privacidad",
    category: "seo",
    severity: "alta",
    why: "Un negocio real necesita páginas legales. Su ausencia delata un sitio generado como demo.",
    fix: "Publicar /terminos y /privacidad reales, enlazadas desde el footer.",
  },
  {
    code: 7,
    id: "em-dashes",
    title: "Guiones largos y dobles guiones en el texto",
    category: "ia",
    severity: "media",
    why: "El uso sistemático de guiones largos y de dobles guiones dentro de las frases es uno de los tics de escritura más reconocibles de los modelos de lenguaje.",
    fix: "Reescribir esas frases con puntuación normal: punto, coma o paréntesis.",
  },
  {
    code: 8,
    id: "no-custom-404",
    title: "Sin página 404 personalizada",
    category: "tecnico",
    severity: "media",
    why: "El 404 por defecto del framework o del hosting muestra que nadie recorrió el sitio más allá de la home.",
    fix: "Crear una 404 con la identidad del sitio y enlaces útiles de vuelta.",
  },
  {
    code: 9,
    id: "empty-view-source",
    title: "View-source vacío (todo renderizado por JS)",
    category: "tecnico",
    severity: "alta",
    why: "Un HTML que sólo tiene un div raíz vacío es el patrón exacto del scaffold de SPA sin SSR. Google puede indexarlo mal y los previews sociales quedan vacíos.",
    fix: "Migrar a SSR/SSG (Next.js, Astro) o al menos prerenderizar el contenido crítico.",
  },
  {
    code: 10,
    id: "vite-react-spa",
    title: "Vite + React para todo el sitio",
    category: "tecnico",
    severity: "media",
    why: "Es el stack por defecto que eligen los generadores de código. Para una web de contenido implica peor SEO y más JS del necesario.",
    fix: "Para una web informativa usar un framework con render en servidor. Reservar la SPA para la parte de aplicación.",
  },
  {
    code: 11,
    id: "fake-testimonials",
    title: "Testimonios que parecen inventados",
    category: "contenido",
    severity: "critica",
    why: "Nombres genéricos, cargos vagos, fotos de stock, sin empresa ni resultado medible: el patrón clásico del testimonio generado.",
    fix: "Usar solo testimonios reales con nombre, foto real, empresa y un resultado concreto. Si no hay, sacar la sección entera.",
  },
  {
    code: 12,
    id: "duplicate-titles",
    title: "Mismo título en todas las páginas",
    category: "seo",
    severity: "alta",
    why: "Indica que el title se puso una sola vez en el layout y nadie lo trabajó por página.",
    fix: "Título único y descriptivo por página, con la keyword y la marca.",
  },
  {
    code: 13,
    id: "no-meta-description",
    title: "Sin meta description",
    category: "seo",
    severity: "media",
    why: "Falta el texto que Google muestra en resultados. Es de las primeras cosas que se saltea una generación automática.",
    fix: "Meta description propia de 140 a 160 caracteres por página.",
  },
  {
    code: 14,
    id: "no-og-image",
    title: "Sin imagen Open Graph",
    category: "seo",
    severity: "media",
    why: "Sin og:image el link compartido aparece como un rectángulo gris. Nadie que promocione su web en serio deja eso así.",
    fix: "Agregar og:image de 1200x630, más og:title, og:description y twitter:card.",
  },
  {
    code: 15,
    id: "no-structured-data",
    title: "Datos no estructurados (sin JSON-LD)",
    category: "seo",
    severity: "media",
    why: "Sin schema.org los buscadores y las IA no pueden entender qué es el sitio ni quién lo firma.",
    fix: "Agregar JSON-LD con Organization o Person, y WebSite.",
  },
  {
    code: 16,
    id: "no-canonical",
    title: "Sin etiqueta canónica",
    category: "seo",
    severity: "baja",
    why: "El canonical evita contenido duplicado entre variantes de URL. Nunca aparece en una web generada de una sola pasada.",
    fix: "Agregar link rel=canonical con la URL absoluta de cada página.",
  },
  {
    code: 17,
    id: "no-llms-txt",
    title: "Sin llms.txt",
    category: "seo",
    severity: "baja",
    why: "El llms.txt le dice a los modelos qué es el sitio y qué pueden citar. Su ausencia indica que no se pensó la capa de IA.",
    fix: "Publicar /llms.txt con la descripción del sitio, las páginas clave y el contacto.",
  },
  {
    code: 18,
    id: "robots-blocks-ai",
    title: "robots.txt bloqueando a las IA",
    category: "seo",
    severity: "media",
    why: "Bloquear GPTBot, ClaudeBot o PerplexityBot sin querer (viene por defecto en varios templates) deja al sitio fuera de las respuestas de IA.",
    fix: "Revisar el robots.txt y permitir explícitamente los bots de IA que interesen.",
  },
  {
    code: 19,
    id: "no-sitemap",
    title: "Sin sitemap",
    category: "seo",
    severity: "media",
    why: "Sin sitemap.xml el rastreo depende de la suerte de los enlaces internos.",
    fix: "Generar /sitemap.xml y referenciarlo desde robots.txt.",
  },
  {
    code: 20,
    id: "no-lang",
    title: "Sin atributo de idioma",
    category: "accesibilidad",
    severity: "media",
    why: "Sin lang en la etiqueta html, los lectores de pantalla leen el contenido con la fonética equivocada y Google no sabe a qué mercado apunta.",
    fix: "Definir el atributo lang en la etiqueta html con el idioma real del contenido.",
  },
  {
    code: 21,
    id: "missing-alt",
    title: "Imágenes sin texto alternativo",
    category: "accesibilidad",
    severity: "media",
    why: "El alt se completa cuando alguien revisa la web imagen por imagen. Las generadas lo dejan vacío o directamente no lo ponen.",
    fix: "Escribir alt descriptivo en toda imagen informativa y alt vacío en las decorativas.",
  },
  {
    code: 22,
    id: "exposed-sourcemaps",
    title: "Sourcemaps expuestos en producción",
    category: "tecnico",
    severity: "alta",
    why: "Publicar los .map deja el código fuente original accesible a cualquiera. Pasa cuando se sube el build de desarrollo sin configurar nada.",
    fix: "Desactivar la generación de sourcemaps públicos en el build de producción.",
  },
  {
    code: 23,
    id: "console-errors",
    title: "Errores en el navegador (recursos rotos)",
    category: "tecnico",
    severity: "alta",
    why: "Scripts, hojas de estilo o imágenes que devuelven 404 rompen la página en silencio. Nadie que haya abierto la consola los dejaría.",
    fix: "Abrir DevTools, corregir cada 404 y cada excepción antes de publicar.",
  },
  {
    code: 24,
    id: "huge-js-bundle",
    title: "Bundle de JavaScript gigante",
    category: "performance",
    severity: "alta",
    why: "Cientos de KB de JS para una web de contenido significa que se importó todo sin criterio.",
    fix: "Code splitting, imports dinámicos, sacar librerías que se usan una sola vez y mover lo estático a HTML.",
  },
  {
    code: 25,
    id: "three-part-solution",
    title: "Sección de solución en 3 partes",
    category: "diseno",
    severity: "media",
    why: "Tres beneficios, tres pasos, tres planes. La IA siempre resuelve en tríos porque calza en un grid de 3 columnas.",
    fix: "Romper el trío: usar la cantidad real de argumentos y darles pesos visuales distintos.",
  },
  {
    code: 26,
    id: "ai-phrases",
    title: "Frases típicas de IA en el texto visible",
    category: "ia",
    severity: "alta",
    why: "Expresiones como en el panorama digital actual, desbloquea el poder de o sumérgete en son vocabulario de modelo, no de persona.",
    fix: "Reescribir esas frases con lenguaje concreto y ejemplos propios.",
  },
  {
    code: 27,
    id: "placeholders",
    title: "Placeholders sin completar",
    category: "contenido",
    severity: "critica",
    why: "Lorem ipsum, INSERTAR AQUÍ o Tu titular acá en producción es la prueba directa de que nadie leyó la web publicada.",
    fix: "Recorrer la web completa y reemplazar cada placeholder por contenido real.",
  },
  {
    code: 28,
    id: "generator-comments",
    title: "Comentarios de generador en el HTML",
    category: "ia",
    severity: "alta",
    why: "Restos como Generated by, Built with v0 o Created with Lovable quedan en el código y confirman el origen.",
    fix: "Limpiar los comentarios del HTML en el build de producción.",
  },
  {
    code: 29,
    id: "generic-layout",
    title: "Estructura visual genérica",
    category: "diseno",
    severity: "alta",
    why: "Hero con gradiente violeta a rosa, grid de 3 cards, Cómo funciona en 3 pasos, pricing de 3 planes, slider de testimonios y footer de 4 columnas: la plantilla que devuelve cualquier generador.",
    fix: "Elegir una estructura propia guiada por el argumento de venta, no por la plantilla. Cambiar paleta, tipografía y ritmo de secciones.",
  },
  {
    code: 30,
    id: "generator-classes",
    title: "Clases y patrones típicos de generadores",
    category: "ia",
    severity: "media",
    why: "rounded-2xl más shadow-lg más gradiente violeta a rosa más íconos lucide es la combinación por defecto de los generadores con Tailwind.",
    fix: "Definir tokens propios de radio, sombra y color en vez de usar los defaults.",
  },
  {
    code: 31,
    id: "generator-meta",
    title: "Meta generator de una herramienta de IA",
    category: "ia",
    severity: "alta",
    why: "El propio HTML declara con qué se hizo: v0, Lovable, Bolt, Framer, Replit, Cursor.",
    fix: "Quitar o reemplazar la meta generator.",
  },
  {
    code: 32,
    id: "generic-hosting",
    title: "Dominio genérico de hosting",
    category: "tecnico",
    severity: "media",
    why: "Publicar en un subdominio de vercel.app o netlify.app sin dominio propio dice que el proyecto nunca pasó de la demo.",
    fix: "Comprar un dominio propio y apuntarlo, con redirect 301 desde el subdominio.",
  },
  {
    code: 33,
    id: "ai-api-calls",
    title: "Llamadas a APIs de IA desde el front",
    category: "tecnico",
    severity: "critica",
    why: "Ver api.openai.com o api.anthropic.com dentro del bundle del cliente casi siempre implica una API key expuesta.",
    fix: "Mover toda llamada a la IA a un endpoint del servidor y sacar la key del cliente.",
  },
  {
    code: 34,
    id: "no-specifics",
    title: "Texto genérico sin datos concretos",
    category: "contenido",
    severity: "alta",
    why: "Sin cifras, sin casos, sin nombres propios, sin fechas y sin fuentes, el texto podría pertenecer a cualquier empresa del mundo.",
    fix: "Meter números reales, nombres, fechas, capturas y enlaces a fuentes verificables.",
  },
  {
    code: 35,
    id: "no-eeat",
    title: "Falta de E-E-A-T (nadie firma la web)",
    category: "contenido",
    severity: "alta",
    why: "Sin Sobre mí, sin foto real, sin contacto claro y sin redes enlazadas, no hay una persona verificable detrás.",
    fix: "Agregar página Sobre, foto real, contacto, redes y prueba social verificable.",
  },
  {
    code: 36,
    id: "a11y-basics",
    title: "Errores de accesibilidad básicos",
    category: "accesibilidad",
    severity: "alta",
    why: "Botones sin nombre accesible, inputs sin label o foco desactivado son fallas que aparecen apenas alguien navega con teclado.",
    fix: "Poner label a cada input, aria-label a los botones de solo ícono y no anular el outline de foco.",
  },
  {
    code: 37,
    id: "poor-performance",
    title: "Performance pobre",
    category: "performance",
    severity: "alta",
    why: "HTML pesado, imágenes sin optimizar y respuesta lenta hunden los Core Web Vitals.",
    fix: "Comprimir e ir a formatos modernos de imagen, definir width y height, usar lazy loading y cachear en CDN.",
  },
  {
    code: 38,
    id: "no-specific-schema",
    title: "Sin schema específico (Organization, FAQ, Article)",
    category: "seo",
    severity: "baja",
    why: "Tener JSON-LD genérico pero no el schema del tipo de negocio deja rich results sin aprovechar.",
    fix: "Agregar el schema que corresponda: Organization o LocalBusiness, Product, Article, FAQPage, BreadcrumbList.",
  },
  {
    code: 39,
    id: "duplicate-urls",
    title: "Títulos o descripciones casi idénticos entre páginas",
    category: "seo",
    severity: "media",
    why: "Páginas que se pisan entre sí en Google: síntoma de contenido replicado en masa.",
    fix: "Diferenciar el contenido y el título de cada URL, o consolidarlas en una sola.",
  },
  {
    code: 40,
    id: "no-cookie-policy",
    title: "Sin política de cookies ni consentimiento",
    category: "seo",
    severity: "media",
    why: "Si el sitio carga analytics o píxeles y no pide consentimiento, además de ser una señal de descuido es un riesgo legal.",
    fix: "Agregar banner de consentimiento y política de cookies, y no cargar los scripts de tracking antes de aceptar.",
  },
  {
    code: 41,
    id: "class-soup",
    title: "Sopa de clases utilitarias sin sistema",
    category: "diseno",
    severity: "baja",
    why: "Elementos con 25 clases o más, repetidas literalmente en cada card, muestran que no hay componentes ni tokens: se generó cada bloque por separado.",
    fix: "Extraer componentes y tokens de diseño; dejar de repetir la misma cadena de utilidades.",
  },
  {
    code: 42,
    id: "single-page-only",
    title: "Sitio de una sola página sin navegación real",
    category: "seo",
    severity: "media",
    why: "Todos los enlaces apuntan a anclas de la misma página. No hay arquitectura de información ni superficie para posicionar.",
    fix: "Separar en páginas reales lo que tiene búsqueda propia: servicios, casos, blog, contacto.",
  },
  {
    code: 43,
    id: "stock-placeholder-images",
    title: "Imágenes de stock o placeholder",
    category: "contenido",
    severity: "media",
    why: "Unsplash, picsum o placehold.co en producción: las fotos nunca se reemplazaron por material propio.",
    fix: "Reemplazar por fotos reales del producto, del equipo o del trabajo hecho.",
  },
  {
    code: 44,
    id: "no-contact",
    title: "Sin datos de contacto reales",
    category: "contenido",
    severity: "alta",
    why: "Sin email, teléfono ni dirección no hay forma de verificar que exista un negocio detrás.",
    fix: "Publicar email real, teléfono o WhatsApp, y ubicación si aplica.",
  },
  {
    code: 45,
    id: "footer-leftovers",
    title: "Restos de plantilla en el footer",
    category: "ia",
    severity: "baja",
    why: "Un Made with heart, un año de copyright hardcodeado y desactualizado, o el nombre del template sin cambiar, son residuos del scaffold.",
    fix: "Escribir el footer a mano, con el año dinámico y los datos reales de la marca.",
  },
];

export const SIGNAL_BY_ID = new Map(SIGNALS.map((s) => [s.id, s]));
